import json
exec(open("make_specs.py").read().split("s(\"canape-enfant")[0])
s("fauteuil-a-bascule-teddy-caramel-repose-pieds",[L("63 cm"),H("99 cm")],["Assise 48 × 48 cm","Dossier 66 cm"],remarques="Pas de profondeur hors tout au tableau")
s("fauteuil-relax-aspect-lin-creme",[L("73 cm"),H("100 cm")],["Profondeur 86 cm (158 cm incliné)","Hauteur d'assise 46 cm"])
s("fauteuil-relax-electrique-gris-compact",[L("60 cm"),H("103 cm")],["Profondeur 65 cm","Accoudoirs à 61 cm du sol"])
s("fauteuil-papasan-pivotant-jardin-creme",[L("97 cm"),H("90 cm")],["Profondeur 87 cm"])
s("pouf-coffre-rond-velours-cotele",[D("Ø 40 cm"),H("41 cm")],["Rangement Ø 33 cm, 30 cm de haut (32 L)"])
s("lot-2-poufs-coffres-gigognes-velours-blanc",[H("24,5 cm","gauche","gauche"),H("20,5 cm","droite")],["Grand pouf Ø 41 cm","Petit pouf Ø 32 cm"],remarques="Deux poufs : diamètres en encart")
s("pouf-macrame-coton-ecru",[D("Ø 45 cm"),H("30 cm")],[])
s("pouf-jute-tresse-raye-naturel",[D("Ø 45 cm"),H("30 cm")],[])
s("repose-pieds-vintage-lin-beige",[L("40 cm"),H("43 cm")],["Profondeur 40 cm"])
s("repose-pieds-banquette-polaire-grise",[L("67 cm"),H("38 cm")],["Profondeur 45 cm","Épaisseur d'assise 12 cm"])
s("petit-repose-pieds-effet-lin-marron-clair",[L("27 cm"),H("26 cm")],["Profondeur 27 cm","Épaisseur d'assise 12 cm"])
s("repose-pieds-cube-lin-creme-poche",[L("35 cm"),H("35 cm")],["Profondeur 35 cm","Poche latérale 35 × 20 cm"])
s("fauteuil-cocon-resine-tressee-avec-pouf",[H("147 cm",[219,82,1137,1782],"gauche"),H("41 cm",[983,1167,1884,1915])],["Fauteuil : 76 × 65 cm au sol","Hauteur d'assise 38 cm","Pouf 66 × 42 × 41 cm"],remarques="Fauteuil et pouf : largeurs en encart")
s("fauteuil-relax-bouclette-creme-pivotant",[L("76 cm"),H("100 cm")],["Profondeur 94 cm (160 cm incliné)","Hauteur d'assise 49,5 cm"])
json.dump(S,open("cotes_specs_reprise.json","w"),ensure_ascii=False,indent=1)
print(len(S))
